version: '3.5'
services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ./data/:/data
    env_file:
        - ".env"
    environment:
        - REDIS_HOST=redisdb
        - REDIS_PORT=6379
    ports:
        - "6379:6379"
    networks:
        - redis-network
  nestjs:
    build: .
    working_dir: /usr/src/app
    restart: always
    ports:
      - "80:3000"      
    depends_on:
      - redis
    networks:
      - redis-network
networks:
  redis-network:
    driver: bridge